In [1]:
pip install tensorflow pandas matplotlib pillow scikit-learn notebook jupyter

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp310-cp310-win_amd64.whl (350.6 MB)
     -------------------                    179.1/350.6 MB 1.5 MB/s eta 0:01:53
Note: you may need to restart the kernel to use updated packages.

ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\urllib3\response.py", line 437, in _error_catcher
    yield
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\urllib3\response.py", line 526, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\commands\install.py", line 400, in run
    requirement_set = resolver.resolve(
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\urllib3\response.py", line 621, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\urllib3\response.py", line 559, in read
    with self._error_catcher():
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "c:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\urllib3\response.py", line 442, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

[notice] A new release of pip available: 22.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import os
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image

In [3]:
dataset_path = r"C:\Users\ASUS\.cache\kagglehub\datasets\emmarex\plantdisease\versions\1\PlantVillage"

In [4]:
classes = os.listdir(dataset_path)

print("Number of Classes:", len(classes))
print("\nClass Names:")

for cls in classes:
    print(cls)

Number of Classes: 16

Class Names:
Pepper__bell___Bacterial_spot
Pepper__bell___healthy
PlantVillage
Potato___Early_blight
Potato___healthy
Potato___Late_blight
Tomato_Bacterial_spot
Tomato_Early_blight
Tomato_healthy
Tomato_Late_blight
Tomato_Leaf_Mold
Tomato_Septoria_leaf_spot
Tomato_Spider_mites_Two_spotted_spider_mite
Tomato__Target_Spot
Tomato__Tomato_mosaic_virus
Tomato__Tomato_YellowLeaf__Curl_Virus

In [5]:
class_df = pd.DataFrame(classes, columns=["Disease Class"])

class_df

                                  Disease Class
0                 Pepper__bell___Bacterial_spot
1                        Pepper__bell___healthy
2                                  PlantVillage
3                         Potato___Early_blight
4                              Potato___healthy
5                          Potato___Late_blight
6                         Tomato_Bacterial_spot
7                           Tomato_Early_blight
8                                Tomato_healthy
9                            Tomato_Late_blight
10                             Tomato_Leaf_Mold
11                    Tomato_Septoria_leaf_spot
12  Tomato_Spider_mites_Two_spotted_spider_mite
13                          Tomato__Target_Spot
14                  Tomato__Tomato_mosaic_virus
15        Tomato__Tomato_YellowLeaf__Curl_Virus

In [6]:
class_df.to_csv("outputs/class_names.csv", index=False)

print("Class names saved successfully.")

Class names saved successfully.

In [9]:
import os

image_count = {}

for cls in classes:
    class_path = os.path.join(dataset_path, cls)

    if os.path.isdir(class_path):
        image_count[cls] = len(os.listdir(class_path))

image_count

{'Pepper__bell___Bacterial_spot': 997,
 'Pepper__bell___healthy': 1478,
 'PlantVillage': 15,
 'Potato___Early_blight': 1000,
 'Potato___healthy': 152,
 'Potato___Late_blight': 1000,
 'Tomato_Bacterial_spot': 2127,
 'Tomato_Early_blight': 1000,
 'Tomato_healthy': 1591,
 'Tomato_Late_blight': 1909,
 'Tomato_Leaf_Mold': 952,
 'Tomato_Septoria_leaf_spot': 1771,
 'Tomato_Spider_mites_Two_spotted_spider_mite': 1676,
 'Tomato__Target_Spot': 1404,
 'Tomato__Tomato_mosaic_virus': 373,
 'Tomato__Tomato_YellowLeaf__Curl_Virus': 3209}

In [10]:
count_df = pd.DataFrame(
    image_count.items(),
    columns=["Disease Class", "Number of Images"]
)

count_df

                                  Disease Class  Number of Images
0                 Pepper__bell___Bacterial_spot               997
1                        Pepper__bell___healthy              1478
2                                  PlantVillage                15
3                         Potato___Early_blight              1000
4                              Potato___healthy               152
5                          Potato___Late_blight              1000
6                         Tomato_Bacterial_spot              2127
7                           Tomato_Early_blight              1000
8                                Tomato_healthy              1591
9                            Tomato_Late_blight              1909
10                             Tomato_Leaf_Mold               952
11                    Tomato_Septoria_leaf_spot              1771
12  Tomato_Spider_mites_Two_spotted_spider_mite              1676
13                          Tomato__Target_Spot              1404
14                  Tomato__Tomato_mosaic_virus               373
15        Tomato__Tomato_YellowLeaf__Curl_Virus              3209

In [11]:
count_df.to_csv("outputs/image_count.csv", index=False)

print("Image count table saved successfully.")

Image count table saved successfully.

In [12]:
total_images = count_df["Number of Images"].sum()

print("Total Classes :", len(count_df))
print("Total Images  :", total_images)

Total Classes : 16
Total Images  : 20654